name: Deploy

on:
  push:
    branches: [ dev, main ]
  # for manual prod trigger
  workflow_dispatch:

jobs:

  test-backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    # CI runs on a clean machine every time
    # services → spin up dependencies (Postgres)
    # env → replace .env file
    # placeholders → prevent crashes for unused services

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: budgetwise_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/budgetwise_test
      JWT_SECRET: test_secret
      JWT_REFRESH_SECRET: test_refresh_secret
      NODE_ENV: test
      SQS_QUEUE_URL: placeholder
      AWS_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: placeholder
      AWS_SECRET_ACCESS_KEY: placeholder
      SES_FROM_EMAIL: placeholder@test.com

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install
    - run: npx prisma generate
    - run: npx prisma migrate deploy
    - run: npm test

  test-frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test


  deploy-frontend:

    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [test-frontend]
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}

      
  deploy-backend:

    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [test-backend]
    # no default: working-directory, since it doesn't run on GitHub runner but on EC2 machine, so working-directory is completely ignored ❌
    # no need to specify services or env here (only for GitHub Actions, not EC2) since EC2 should already have: 1. DB installed locally or using RDS, 2. .env file on EC2, 3. Deploy script just assumes everything is already configured

    # steps:
    # - uses: actions/checkout@v4
    #   with:
    #     node-version: '20'
    # - name: SSH into EC2 and deploy
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ubuntu
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     script: |
    #       cd ~/BudgetWise/backend
    #       git pull origin main
    #       npm install
    #       pm2 restart budgetwise-backend

    # New scripts section for Lambda deployment
    steps:
      - uses: actions/checkout@v4
      # The original deploy-backend job, it didn't have setup-node because it wasn't running npm install on the GitHub runner — it was SSHing into EC2 and running commands there. EC2 already had Node installed.
      # Now we're running npm install on the GitHub runner itself before zipping, so we need Node available on the runner — hence setup-node.
      # The frontend and test jobs already had it for the same reason — they run npm install on the runner directly.
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install production dependencies
        working-directory: backend
        run: npm install --omit=dev

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Package and deploy to Lambda
        working-directory: backend
        run: |
          zip -r ../lambda-code.zip . \
            --exclude "*.git*" \
            --exclude "*node_modules/prisma/build*" \
            --exclude "*node_modules/prisma/dist*" \
            --exclude "*node_modules/.cache*" \
            --exclude "*node_modules/effect*" \
            --exclude "tests/*" \
            --exclude "workers/*"

          aws s3 cp ../lambda-code.zip s3://budgetwise-frontend-bucket/lambda-code.zip

          aws lambda update-function-code \
            --function-name budgetwise-backend \
            --s3-bucket budgetwise-frontend-bucket \
            --s3-key lambda-code.zip
